POST {{auction_host}}/auction
Content-Type: application/json

{
  "title": "Drum Set"
}

###

GET {{auction_host}}/auctions

###

GET {{auction_host}}/auction/920e88c8-41fd-4c0c-82a5-2ac0da3a3d58

###

PATCH {{auction_host}}/auction/920e88c8-41fd-4c0c-82a5-2ac0da3a3d58/bid
Content-Type: application/json

{
  "amount": "1.40"
}

###

GET {{hello_host}}/hello

