POST {{auction_host}}/auction
Content-Type: application/json

{
  "title": "TimmyGeekMonkey"
}

###

GET {{auction_host}}/auctions

###

GET {{auction_host}}/auction/6a414d05-7d04-4047-aa19-639d7d9672d9

###

GET {{hello_host}}/hello
